# playbook.yml:
---
- name: "Laptop Configuration"
  hosts: 127.0.0.1
  connection: local
  tasks:
    # global upgrade
    - name: Update all packages to their latest version
      apt:
        name: "*"
        state: latest

    # git
    - name: Install git
      apt:
        name: git
        state: present
        update_cache: yes

    # zsh
    - name: Install zsh
      apt:
        name: zsh
        state: present
        update_cache: yes
    - name: Set zsh as default
      shell: chsh -s $(which zsh)

    # MEGAsync
    - name: Download MEGAsync
      get_url:
        url: https://mega.nz/linux/MEGAsync/xUbuntu_20.04/amd64/megasync-xUbuntu_20.04_amd64.deb
        dest: /tmp/megasync.deb
        mode: 700
    - name: Install MEGAsync
      apt:
        deb: /tmp/megasync.deb

    # Forti client
    - name: Adds fortinet apt key
      apt_key:
        url: https://repo.fortinet.com/repo/6.4/ubuntu/DEB-GPG-KEY
        state: present
    - name: Add fortinet repository into sources list
      apt_repository:
        repo: deb [arch=amd64] https://repo.fortinet.com/repo/6.4/ubuntu/ /bionic multiverse
        state: present
    - name: Run the equivalent of "apt-get update" for fortinet
      apt:
        update_cache: yes
    - name: Install fortclient
      apt:
        name: forticlient
        state: present