# playbook.yml:
---
- name: "Laptop Configuration"
  hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Update all packages to their latest version
      apt:
        name: "*"
        state: latest

    - name: Install git
      apt:
        name: git
        state: present
        update_cache: yes

    - name: Install zsh
      apt:
        name: zsh
        state: present
        update_cache: yes
    - name: Set zsh as default
      shell: chsh -s $(which zsh)

    - name: Download MEGAsync
      get_url:
        url: https://mega.nz/linux/MEGAsync/xUbuntu_20.04/amd64/megasync-xUbuntu_20.04_amd64.deb
        dest: /tmp/megasync.deb
        mode: 700

    - name: Install MEGAsync
      apt:
        deb: /tmp/megasync.deb
