- name: Installing Zsh and git
  apt: pkg=zsh,git state=latest
  register: installation
  become: false

- name: Check if .zshrc exists
  stat:
    path: ~/.zshrc
  register: stat_rc_result
  become: false

- name: Check if .oh-my-zsh exists
  stat:
    path: ~/.oh-my-zsh
  register: stat_oh_my_zsh_result
  become: false

- name: Cloning  oh-my-zsh
  git:
    repo=https://github.com/robbyrussell/oh-my-zsh
    dest=~/.oh-my-zsh
  when: not stat_oh_my_zsh_result.stat.exists
  become: false

- name: Creating new ~/.zshrc
  copy:
    src=~/.oh-my-zsh/templates/zshrc.zsh-template
    dest=~/.zshrc
  when: not stat_rc_result.stat.exists
  become: false

- name: Change shell to zsh
  expect:
    command: "chsh -s /usr/bin/zsh"
    responses:
      (?i)password: "{{ my_password }}"
    creates: ".shell_is_zsh"